// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EnsurePeriodicConfig() {
  return window['go']['main']['App']['EnsurePeriodicConfig']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function PrepareCertificate() {
  return window['go']['main']['App']['PrepareCertificate']();
}

export function SelectRootDirectory() {
  return window['go']['main']['App']['SelectRootDirectory']();
}

export function StartFileProxy(arg1) {
  return window['go']['main']['App']['StartFileProxy'](arg1);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function StopFileProxy() {
  return window['go']['main']['App']['StopFileProxy']();
}
