// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Login(arg1:string,arg2:string,arg3:string):Promise<main.AppStatus>;

export function Logout():Promise<main.AppStatus>;

export function OpenWebURL():Promise<main.AppStatus>;

export function SelectRootDirectory():Promise<main.AppStatus>;

export function SetAPIBaseURL(arg1:string):Promise<main.AppStatus>;

export function StartFileProxy(arg1:main.StartOptions):Promise<main.AppStatus>;

export function StartFileProxyWeb(arg1:main.StartOptions):Promise<main.AppStatus>;

export function Status():Promise<main.AppStatus>;

export function StopFileProxy():Promise<main.AppStatus>;

export function StopFileProxyWeb():Promise<main.AppStatus>;
